local_costmap:
  global_frame: /map #To inflate obstacles
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0 #6
  height: 10.0 #6
  resolution: 0.05 #0.01
  transform_tolerance: 1.0

  plugins:
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
