local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0 #6
  height: 10.0 #6
  resolution: 0.05 #0.01
  transform_tolerance: 1.0

  plugins:
    - {name: ultrasonic,   type: "range_sensor_layer::RangeSensorLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  ultrasonic:
    clear_threshold:    0.46
    mark_threshold:     0.8
    no_readings_timeout: 2.0
  # ns:     /mobile_base/sensors/sonars
    topics: ["/SLIT_range", "/SLDD_range", "/STD_range", "/SDI_range","/SLID_range","/SDD_range","/SLDT_range","/STI_range"]
